import React, { useEffect, useState } from 'react';
import { useNav } from '../context/NavContext';
import { apiService, type Recommendation } from '../services/api';

import { ApprovalStatusBadge } from '../components/ui/ApprovalStatusBadge';
import { SuccessToast } from '../components/ui/SuccessToast';
import { ApprovalDialog } from '../components/ui/ApprovalDialog';
import { RejectDialog } from '../components/ui/RejectDialog';
import { ModifyRecommendationDialog } from '../components/ui/ModifyRecommendationDialog';
import { 
  Check, 
  X, 
  Edit, 
  AlertCircle, 
  Sparkles, 
  Calendar,
  Activity,
  RefreshCw,
  TrendingUp,
  Loader2,
  HelpCircle,
  Zap,
  ArrowRight
} from 'lucide-react';

export const Recommendations: React.FC = () => {
  const { selectedCustomerId } = useNav();
  const [recommendations, setRecommendations] = useState<(Recommendation & { customer_name: string, customer_health: number, customer_risk: string })[]>([]);
  const [selectedRec, setSelectedRec] = useState<(Recommendation & { customer_name: string, customer_health: number, customer_risk: string }) | null>(null);
  
  // Dialog States
  const [showApproveDialog, setShowApproveDialog] = useState(false);
  const [showRejectDialog, setShowRejectDialog] = useState(false);
  const [showModifyDialog, setShowModifyDialog] = useState(false);
  
  // Toast Notification State
  const [toastMessage, setToastMessage] = useState<string | null>(null);
  const [toastType, setToastType] = useState<'success' | 'danger' | 'warning'>('success');
  
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchRecommendations = async () => {
    setLoading(true);
    setError(null);
    try {
      const customersList = await apiService.getCustomers();
      const allRecs: any[] = [];
      
      // Fetch recommendations for all customers to show in queue
      await Promise.all(customersList.map(async (c) => {
        const detail = await apiService.getCustomer(c.id);
        detail.recommendations.forEach(r => {
          allRecs.push({
            ...r,
            customer_name: c.name,
            customer_health: c.health_score,
            customer_risk: c.risk_level
          });
        });
      }));
      
      // Sort recommendations: newest first
      const sorted = allRecs.sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime());
      setRecommendations(sorted);
      
      // Pre-select recommendation based on selectedCustomerId or choose first
      if (sorted.length > 0) {
        if (selectedCustomerId) {
          const match = sorted.find(r => r.customer_id === selectedCustomerId);
          setSelectedRec(match || sorted[0]);
        } else {
          setSelectedRec(sorted[0]);
        }
      } else {
        setSelectedRec(null);
      }
      setLoading(false);
    } catch (err) {
      setError("Failed to load recommendation center queues.");
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchRecommendations();
  }, [selectedCustomerId]);

  const handleDecisionCompleted = (status: 'approved' | 'rejected' | 'modified', detailsMessage?: string) => {
    setToastType(status === 'approved' ? 'success' : (status === 'rejected' ? 'danger' : 'warning'));
    setToastMessage(detailsMessage || `Recommendation successfully ${status}!`);
    fetchRecommendations(); // reload queue
  };

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[70vh] space-y-3">
        <Loader2 className="w-8 h-8 animate-spin text-primary" />
        <span className="text-xs text-neutral-400">Syncing recommendation queue...</span>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Title */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-bold text-neutral-900 dark:text-white tracking-tight">
            Recommendation Decision Center
          </h1>
          <p className="text-xs text-neutral-450 dark:text-neutral-500 mt-0.5">
            Audit and approve Next Best Actions generated by agent synthesis models.
          </p>
        </div>
        <button 
          onClick={fetchRecommendations}
          className="flex items-center gap-1.5 px-3 py-1.5 border border-neutral-200 dark:border-neutral-800 rounded-lg text-xs font-semibold text-neutral-600 dark:text-neutral-350 bg-white dark:bg-neutral-900 hover:bg-neutral-50 dark:hover:bg-neutral-950 transition-all duration-150"
        >
          <RefreshCw className="w-3.5 h-3.5" /> Sync Queue
        </button>
      </div>

      {error && (
        <div className="flex items-center gap-3 p-4 rounded-xl bg-danger-light/20 border border-danger/30 text-danger-dark dark:text-danger-light">
          <AlertCircle className="w-5 h-5 text-danger flex-shrink-0" />
          <p className="text-xs font-semibold leading-tight">{error}</p>
        </div>
      )}

      {/* Main Layout Split */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Left Side Pane: Queue List */}
        <div className="p-4 border border-neutral-200 dark:border-neutral-800 bg-white dark:bg-neutral-900 rounded-xl shadow-sm space-y-4 max-h-[75vh] overflow-y-auto">
          <h3 className="text-xs font-bold text-neutral-950 dark:text-white uppercase tracking-wider px-2">
            Pending Action Queue ({recommendations.filter(r => r.status === 'pending').length})
          </h3>
          
          <div className="space-y-2">
            {recommendations.map((rec) => {
              const isSelected = selectedRec?.id === rec.id;
              return (
                <div
                  key={rec.id}
                  onClick={() => setSelectedRec(rec)}
                  className={`p-3 rounded-xl border text-left cursor-pointer transition-all duration-150 ${
                    isSelected
                      ? 'border-primary bg-primary/5 shadow-sm'
                      : 'border-neutral-100 dark:border-neutral-850 hover:bg-neutral-50/50 dark:hover:bg-neutral-950/20'
                  }`}
                >
                  <div className="flex items-center justify-between">
                    <span className="text-xs font-bold text-neutral-900 dark:text-white truncate">
                      {rec.customer_name}
                    </span>
                    <ApprovalStatusBadge status={rec.status} />
                  </div>
                  <h4 className="text-[11px] font-semibold text-neutral-600 dark:text-neutral-350 line-clamp-1 mt-1">
                    {rec.primary_action}
                  </h4>
                  <div className="flex items-center justify-between mt-2.5 pt-2 border-t border-neutral-100/50 dark:border-neutral-800/40 text-[9px] text-neutral-400 dark:text-neutral-500 font-semibold">
                    <span>Health: {rec.customer_health}%</span>
                    <span>Confidence: {rec.confidence_score * 100}%</span>
                  </div>
                </div>
              );
            })}

            {recommendations.length === 0 && (
              <p className="text-xs text-neutral-400 dark:text-neutral-500 text-center py-10">
                No active recommendations. Click "Run Decision Agents" on a customer workspace to generate some!
              </p>
            )}
          </div>
        </div>

        {/* Right Side Pane: Detailed Audit Workscreen */}
        <div className="lg:col-span-2 space-y-6">
          {selectedRec ? (
            <div className="space-y-6">
              
              {/* Account Overview Header */}
              <div className="p-5 border border-neutral-200 dark:border-neutral-800 bg-white dark:bg-neutral-900 rounded-xl shadow-sm flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                <div>
                  <div className="flex items-center gap-2">
                    <h2 className="text-sm font-bold text-neutral-950 dark:text-white">
                      {selectedRec.customer_name}
                    </h2>
                    <ApprovalStatusBadge status={selectedRec.status} />
                  </div>
                  <div className="flex items-center gap-4 text-[10px] text-neutral-400 dark:text-neutral-500 font-semibold mt-1">
                    <span className="flex items-center gap-1"><Activity className="w-3.5 h-3.5" /> Health: {selectedRec.customer_health}%</span>
                    <span className="flex items-center gap-1"><TrendingUp className="w-3.5 h-3.5" /> Risk Level: {selectedRec.customer_risk}</span>
                    <span className="flex items-center gap-1"><Calendar className="w-3.5 h-3.5" /> Generated: {new Date(selectedRec.created_at).toLocaleDateString()}</span>
                  </div>
                </div>

                {/* Decision CTA Buttons */}
                {selectedRec.status === 'pending' && (
                  <div className="flex items-center gap-2 flex-shrink-0">
                    <button
                      onClick={() => setShowApproveDialog(true)}
                      className="flex items-center justify-center gap-1.5 px-3.5 py-2 bg-success text-white rounded-lg text-xs font-bold shadow-sm shadow-success/20 hover:bg-success-dark active:scale-[0.98] transition-all"
                    >
                      <Check className="w-3.5 h-3.5" /> Approve
                    </button>
                    <button
                      onClick={() => setShowRejectDialog(true)}
                      className="flex items-center justify-center gap-1.5 px-3.5 py-2 bg-danger text-white rounded-lg text-xs font-bold shadow-sm shadow-danger/20 hover:bg-danger-dark active:scale-[0.98] transition-all"
                    >
                      <X className="w-3.5 h-3.5" /> Reject
                    </button>
                    <button
                      onClick={() => setShowModifyDialog(true)}
                      className="flex items-center justify-center gap-1.5 px-3.5 py-2 border border-neutral-200 dark:border-neutral-800 rounded-lg text-xs font-semibold text-neutral-500 hover:text-neutral-950 dark:hover:text-white bg-white dark:bg-neutral-900 hover:bg-neutral-50 dark:hover:bg-neutral-950 active:scale-[0.98] transition-all"
                    >
                      <Edit className="w-3.5 h-3.5" /> Modify
                    </button>
                  </div>
                )}
              </div>

              {/* Predictive Simulation Impact Header */}
              <div className="p-5 border border-neutral-250 dark:border-neutral-800 bg-neutral-50/50 dark:bg-neutral-950/20 rounded-xl shadow-sm space-y-3">
                <div className="flex items-center gap-2 text-primary font-bold">
                  <Zap className="w-4 h-4 text-primary" />
                  <span className="text-[10px] font-bold uppercase tracking-wider">Predictive Agent Simulation</span>
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 divide-y sm:divide-y-0 sm:divide-x divide-neutral-200/50 dark:divide-neutral-800">
                  <div className="pb-2 sm:pb-0">
                    <span className="text-[9px] text-neutral-450 uppercase font-semibold">Renewal Probability</span>
                    <p className="text-xs font-bold text-neutral-900 dark:text-white mt-1 flex items-center gap-2">
                      <span className="text-neutral-400 line-through text-[10px] font-normal">62%</span>
                      <ArrowRight className="w-3 h-3 text-neutral-400" />
                      <span className="text-success text-sm font-bold">89%</span>
                    </p>
                  </div>
                  <div className="py-2 sm:py-0 sm:pl-4">
                    <span className="text-[9px] text-neutral-450 uppercase font-semibold">Health Score Change</span>
                    <p className="text-xs font-bold text-neutral-900 dark:text-white mt-1 flex items-center gap-2">
                      <span className="text-neutral-400 line-through text-[10px] font-normal">{selectedRec.customer_health}%</span>
                      <ArrowRight className="w-3 h-3 text-neutral-400" />
                      <span className="text-success text-sm font-bold">{Math.min(100, selectedRec.customer_health + 25)}%</span>
                    </p>
                  </div>
                  <div className="pt-2 sm:pt-0 sm:pl-4">
                    <span className="text-[9px] text-neutral-450 uppercase font-semibold">Risk Level Reduction</span>
                    <p className="text-[11px] font-semibold text-neutral-700 dark:text-neutral-350 mt-1">
                      High Churn Risk <span className="text-neutral-400">→</span> <span className="text-success font-bold">Low Risk</span>
                    </p>
                  </div>
                </div>
              </div>

              {/* Recommendation Comparison Cards */}
              <div className="space-y-3">
                <h3 className="text-xs font-bold text-neutral-950 dark:text-white uppercase tracking-wider">Recommendation Comparison</h3>
                <div className="grid grid-cols-1 xl:grid-cols-3 gap-6">
                  {/* Option 1: Primary Action */}
                  <div className="p-5 border-2 border-primary bg-primary/5 rounded-xl space-y-4 relative shadow-sm">
                    <span className="absolute -top-3 left-4 bg-primary text-white text-[8px] font-bold uppercase px-2 py-0.5 rounded-full border border-primary">Primary Action</span>
                    <div className="space-y-2 mt-1">
                      <h4 className="text-xs font-bold text-neutral-955 dark:text-white leading-snug">{selectedRec.primary_action}</h4>
                      <p className="text-[10px] text-neutral-500 leading-relaxed line-clamp-3">{selectedRec.reasoning}</p>
                    </div>

                    <div className="grid grid-cols-2 gap-3 pt-3 border-t border-neutral-200/50 text-[9px] font-bold">
                      <div>
                        <span className="text-neutral-400 uppercase text-[8px] block">Success Rate</span>
                        <span className="text-neutral-800 dark:text-neutral-200">89%</span>
                      </div>
                      <div>
                        <span className="text-neutral-400 uppercase text-[8px] block">Impact</span>
                        <span className="text-primary uppercase">{selectedRec.business_impact}</span>
                      </div>
                      <div>
                        <span className="text-neutral-400 uppercase text-[8px] block">Risk Level</span>
                        <span className="text-success uppercase">Low</span>
                      </div>
                      <div>
                        <span className="text-neutral-400 uppercase text-[8px] block">Confidence</span>
                        <span className="text-neutral-805 dark:text-neutral-250">{selectedRec.confidence_score * 100}%</span>
                      </div>
                    </div>
                  </div>

                  {/* Option 2: Alternative 1 */}
                  <div className="p-5 border border-neutral-150 dark:border-neutral-850 bg-white dark:bg-neutral-900 rounded-xl space-y-4 shadow-sm hover:border-neutral-250 transition-colors">
                    <span className="bg-neutral-100 dark:bg-neutral-805 text-neutral-550 text-[8px] font-bold uppercase px-2 py-0.5 rounded-full border border-neutral-200/60 inline-block">Alternative Option 1</span>
                    <div className="space-y-2">
                      <h4 className="text-xs font-bold text-neutral-800 dark:text-neutral-250 leading-snug">Propose 12-Month Extension with 5% Premium Seats Restructure</h4>
                      <p className="text-[10px] text-neutral-550 leading-relaxed line-clamp-3">Offer a short-term contract expansion of 5% additional licenses at current rates, while keeping the renewal window open for further restructuring negotiations in Q3.</p>
                    </div>

                    <div className="grid grid-cols-2 gap-3 pt-3 border-t border-neutral-100 dark:border-neutral-800 text-[9px] font-bold">
                      <div>
                        <span className="text-neutral-400 uppercase text-[8px] block">Success Rate</span>
                        <span className="text-neutral-750 dark:text-neutral-350">72%</span>
                      </div>
                      <div>
                        <span className="text-neutral-400 uppercase text-[8px] block">Impact</span>
                        <span className="text-neutral-750 dark:text-neutral-350 uppercase">Medium</span>
                      </div>
                      <div>
                        <span className="text-neutral-400 uppercase text-[8px] block">Risk Level</span>
                        <span className="text-warning uppercase">Medium</span>
                      </div>
                      <div>
                        <span className="text-neutral-400 uppercase text-[8px] block">Confidence</span>
                        <span className="text-neutral-755 dark:text-neutral-350">80%</span>
                      </div>
                    </div>
                  </div>

                  {/* Option 3: Alternative 2 */}
                  <div className="p-5 border border-neutral-150 dark:border-neutral-850 bg-white dark:bg-neutral-900 rounded-xl space-y-4 shadow-sm hover:border-neutral-250 transition-colors">
                    <span className="bg-neutral-100 dark:bg-neutral-805 text-neutral-555 text-[8px] font-bold uppercase px-2 py-0.5 rounded-full border border-neutral-200/60 inline-block">Alternative Option 2</span>
                    <div className="space-y-2">
                      <h4 className="text-xs font-bold text-neutral-800 dark:text-neutral-250 leading-snug">Schedule Technical Architecture Optimization and Escalation Sync</h4>
                      <p className="text-[10px] text-neutral-550 leading-relaxed line-clamp-3">Prioritize engineering ticket resolutions for Webhook latency errors. Run optimization audit first before proposing billing changes to build technical trust.</p>
                    </div>

                    <div className="grid grid-cols-2 gap-3 pt-3 border-t border-neutral-100 dark:border-neutral-800 text-[9px] font-bold">
                      <div>
                        <span className="text-neutral-400 uppercase text-[8px] block">Success Rate</span>
                        <span className="text-neutral-750 dark:text-neutral-350">65%</span>
                      </div>
                      <div>
                        <span className="text-neutral-400 uppercase text-[8px] block">Impact</span>
                        <span className="text-neutral-750 dark:text-neutral-350 uppercase">Medium</span>
                      </div>
                      <div>
                        <span className="text-neutral-400 uppercase text-[8px] block">Risk Level</span>
                        <span className="text-success uppercase">Low</span>
                      </div>
                      <div>
                        <span className="text-neutral-400 uppercase text-[8px] block">Confidence</span>
                        <span className="text-neutral-755 dark:text-neutral-350">70%</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              {/* Explainability Panel */}
              <div className="p-6 border border-neutral-200 dark:border-neutral-800 bg-white dark:bg-neutral-900 rounded-xl shadow-sm space-y-5">
                <div className="flex items-center gap-2 text-neutral-450 dark:text-neutral-550 border-b border-neutral-100 dark:border-neutral-850 pb-2">
                  <HelpCircle className="w-4 h-4 text-primary animate-pulse" />
                  <span className="text-xs font-bold text-neutral-950 dark:text-white uppercase tracking-wider">AI Explainability Audit Panel</span>
                </div>

                <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                  {/* Explanatory blocks */}
                  <div className="lg:col-span-2 space-y-4 text-xs font-semibold">
                    <div>
                      <h4 className="font-bold text-neutral-800 dark:text-neutral-250 mb-1">Why this recommendation?</h4>
                      <p className="text-neutral-600 dark:text-neutral-350 leading-relaxed font-medium">
                        The Primary Action is recommended because client renewal is highly sensitive to pricing. Offering a structured volume discount directly addresses the main churn threat (Salesforce) while guaranteeing ACV through a 2-year commitment.
                      </p>
                    </div>

                    <div>
                      <h4 className="font-bold text-neutral-800 dark:text-neutral-250 mb-1">Customer Signals Detected</h4>
                      <ul className="list-disc pl-4 space-y-1.5 text-neutral-500 dark:text-neutral-400 font-bold">
                        <li>Customer budget constraint & Salesforce review mention.</li>
                        <li>Overdue invoice of 18 days indicates pricing bottlenecks.</li>
                        <li>30% license utilization drop in usage history.</li>
                      </ul>
                    </div>

                    <div>
                      <h4 className="font-bold text-neutral-800 dark:text-neutral-250 mb-1">Supporting Evidence / Transcript Excerpt</h4>
                      <div className="p-3 bg-neutral-50 dark:bg-neutral-950 rounded border border-neutral-100 dark:border-neutral-850 font-mono text-[10px] text-neutral-500 leading-relaxed">
                        "{selectedRec.evidence ? selectedRec.evidence.slice(0, 150) + '...' : 'No supporting evidence available.'}"
                      </div>
                    </div>

                    <div>
                      <h4 className="font-bold text-neutral-800 dark:text-neutral-250 mb-1">Knowledge Base References</h4>
                      <div className="flex gap-2 flex-wrap">
                        <span className="px-2 py-0.5 border border-primary/20 bg-primary/5 rounded text-[9px] font-bold text-primary uppercase">PLB-292: Competitor Defend Plan</span>
                        <span className="px-2 py-0.5 border border-primary/20 bg-primary/5 rounded text-[9px] font-bold text-primary uppercase">PLB-103: Renewal Escalation pricing</span>
                      </div>
                    </div>
                  </div>

                  {/* Confidence Breakdown progress bars */}
                  <div className="p-5 bg-neutral-50/50 dark:bg-neutral-950/20 border border-neutral-100 dark:border-neutral-850 rounded-xl space-y-4">
                    <div>
                      <h4 className="text-[10px] font-bold text-neutral-450 uppercase tracking-tight">Confidence Weight Split</h4>
                      <span className="text-[9px] text-neutral-400 block mt-0.5">Calculated consensus weight attribution</span>
                    </div>

                    <div className="space-y-3">
                      {[
                        { label: "Transcript Dialogue", weight: 35, color: "bg-blue-500" },
                        { label: "CRM Billing & Overdue", weight: 20, color: "bg-indigo-500" },
                        { label: "Support ticket logs", weight: 20, color: "bg-rose-500" },
                        { label: "Product Usage trend", weight: 15, color: "bg-cyan-500" },
                        { label: "Historical memories", weight: 10, color: "bg-emerald-500" }
                      ].map((item, idx) => (
                        <div key={idx} className="space-y-1">
                          <div className="flex justify-between text-[9px] font-bold text-neutral-600 dark:text-neutral-400">
                            <span>{item.label}</span>
                            <span>{item.weight}%</span>
                          </div>
                          <div className="w-full bg-neutral-200 dark:bg-neutral-800 rounded-full h-1.5 animate-pulse">
                            <div className={`${item.color} h-1.5 rounded-full`} style={{ width: `${item.weight}%` }} />
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              </div>

            </div>
          ) : (
            <div className="p-16 border border-neutral-200 dark:border-neutral-800 bg-white dark:bg-neutral-900 rounded-xl shadow-sm text-center">
              <Sparkles className="w-8 h-8 text-neutral-350 dark:text-neutral-500 mx-auto mb-4 animate-pulse" />
              <p className="text-xs text-neutral-450 dark:text-neutral-500">
                Please select a recommendation from the queue to start audit review workspace.
              </p>
            </div>
          )}
        </div>

      </div>

      {/* Dialog Confirmations rendering */}
      {selectedRec && (
        <>
          <ApprovalDialog
            recommendationId={selectedRec.id}
            customerName={selectedRec.customer_name}
            isOpen={showApproveDialog}
            onClose={() => setShowApproveDialog(false)}
            onSuccess={() => handleDecisionCompleted('approved', `Recommendation for ${selectedRec.customer_name} approved successfully!`)}
          />

          <RejectDialog
            recommendationId={selectedRec.id}
            customerName={selectedRec.customer_name}
            isOpen={showRejectDialog}
            onClose={() => setShowRejectDialog(false)}
            onSuccess={(reason) => handleDecisionCompleted('rejected', `Recommendation for ${selectedRec.customer_name} rejected. Reason: ${reason}`)}
          />

          <ModifyRecommendationDialog
            recommendationId={selectedRec.id}
            customerName={selectedRec.customer_name}
            currentAction={selectedRec.primary_action}
            currentPriority={selectedRec.customer_risk}
            isOpen={showModifyDialog}
            onClose={() => setShowModifyDialog(false)}
            onSuccess={(actionText, priority, _followUp, _notes) => handleDecisionCompleted('modified', `Recommendation for ${selectedRec.customer_name} overridden. New Action: '${actionText}', priority: '${priority}'`)}
          />
        </>
      )}

      {/* Success Toast Notifications overlay */}
      {toastMessage && (
        <SuccessToast 
          message={toastMessage} 
          type={toastType} 
          onClose={() => setToastMessage(null)} 
        />
      )}

    </div>
  );
};
